#!/usr/bin/perl -w
use strict;
use Getopt::Long;


### brief usage
sub usage {
	print 
		"Usage:","\n",
		"\t","perl task4.pl -i data.txt -o output.txt -mr-min 1000 -mr-max 1550  -bin 50 -error 1.2Da -ion-with P M -ion-start M","\n",
		"\t","-man","\t\t","read complete manual page","\n",
		"\t","-h/help","\t\t","read brief usage","\n",
		"Mandatory Parameters:","\n",
		"\t","-i","\t\t\t","input file","\n",
		"\t","-o","\t\t\t","output file","\n",
		"Options:","\n",
		"\t","-mr-max","\t\t\t","upper limit of mass range (Default: the minimum m/z value of the input data)","\n",
		"\t","-mr-min","\t\t\t","lower limit of mass range (Default: the maximum m/z value of the input data)","\n",
		"\t","-bin","\t\t\t","bin size (Default: bin size = 50)","\n",
		"\t","-error","\t\t\t","give value of mass error (ppm/Da) ex.0.5Da/0.5ppm (Default: mass error = 0 Da)","\n",
		"\t","-ion-start","\t\t","only calculate sequences start with specific amino acids","\n",
		"\t","-ion-with","\t\t","only calculate sequences include specific amino acids","\n";
		
}

sub manpage {
	print 
	"This program is working on the relationship between m/z value and peptide counts.","\n",
	"The program take in the mass file which should contains protein name, peptide counts, mass-to-charge value, the charge of ion, the number of cleavages and sequence. ",
	"Finally, the program will output a file which contains two columns represents m/z values and relevant peptide counts. The output file can be easily used for plotting a histogram in R or any other tools you would like to use. ", 
	"There are three main analysis in this program:","\n",
	"\t","1) ion pattern match","\n",
	"\t\t","Program can identify sequences with specified amino acid in the start of the sequence or sequence contains one or several specified amino acids. User should use shortcut name of amino acids in the command line by -ion-start and -ion-with options. If -ion-start and -ion-with option are not specified, the program won't do this ion-pattern-match part.","\n",
	"\t","2) mass accuracy modelling","\n",
	"\t\t","Users should indicate the mass error value if the mass error is known. -error option is used to define the mass error value. The program can accecpt two units of mass error: Da or ppm. When user defines the mass error, the units should be indicated too or the program will take it as an error. When the unit is 'Da', the program will use the following formula to modify the mass-to-charge value:[exact mass = accurate mass + mass error]. When the unit is 'ppm', program will using the following formula: [mass error = (exact mass - accurate mass)* 10^6 / exact mass]. The modified exact mass will still in unit Da.","\n",
	"\t","3) calculate peptide counts in bins by sliding window","\n";
	"\t\t","Users can define the mass range by -mr-max and -mr-min and define the bin size by -bin. The program will use a sliding window which is as big as the defined bin size, and go over all the data in the mass range. Every bin represents the center position of the bin. For example, if the bin size is 50, the gap between two center position will be 25 which mean there is an half-bin-size overlap between every neighbouring bins. The program will count up all peptides number in every bin and output them.","\n",
	"\t","Options not in mandatory parameter can be remained undefined."
	
	
	
	
}

### read opts and set default values
GetOptions(
	'i=s' => \(my $filename_input=""),
	'o=s' => \(my $filename_output=""),
	'mr-max=s' => \my $mass_range_max, 
	'mr-min=s' => \my $mass_range_min, 
	'bin=s' => \(my $bin_size = 50),
	'error=s' => \(my $error = 0), 
	'ion-start=s' => \(my $ion_start = ""),
	'ion-with=s{,}' => \my @ion_with,
	'help|h' => \my $help,
) or usage();

### print usage while -help/-h
if ($help) {
	exit usage();
}

### check mandatory
if ($filename_input eq "") {
	print "\n","input file name should be given!","\n\n";
	usage();
	exit;
}
if ($filename_output eq "") {
	print "\n","output file name should be given!","\n\n";
	usage();
	exit;
}

### read input file into an array of array
open(IFILE,$filename_input) or die "unable to open the file\n";
my (@mass_data,@line);
my ($line,$line_array,$mass_data);
my $ion_with_each;
while ($line_array = <IFILE>) {
	chomp($line_array);
	@line = split ("\t",$line_array);
	#push (@_,$line);
	$line++;
    for ( my $i=0; $i< @line; $i++ ) {
	    $mass_data[$line-1][$i] = $line[$i];
	}
}
close IFILE;


##################################################
############## ion pattern match #################
##################################################

sub get_mass_start_with {
	my (@data) = @_;
	my (@newdata);
	my ($amino) = $ion_start;
	my ($num) = 0 ;
	for (my $i =0; $i<@data;$i++) {
		if ($data[$i][5] =~ /^$amino/) {
			for (my $j=0; $j<6; $j++) {
				$newdata[$num][$j] = $data[$i][$j];
			}
			$num++;
		}
	} 
	return @newdata;
}

sub get_mass_include {
	my (@data) = @_;
	my (@newdata);
	my ($amino) = $ion_with_each;
	my ($num) = 0;
	for (my $i =0; $i<@data;$i++) {
		if ($data[$i][5] =~ /$amino/) {			
			for (my $j=0; $j<6; $j++) {
				$newdata[$num][$j] = $data[$i][$j];				
			}
			$num++;
		}
	} 
	return @newdata;
}

if ($ion_start ne "") {
	@mass_data = get_mass_start_with(@mass_data);
}

if (scalar(@ion_with) > 0) {
	for (my $i=0;$i<@ion_with;$i++) {
	my $ion_with_each = $ion_with[$i];
	@mass_data = get_mass_include(@mass_data);
	}
}

###################################################
############# process mass error ##################
###################################################

#convert therotic mass value into exact mass value by using Da/ppm mass accuracy
if ($error != 0) {
	my ($mass_error,$type);
	if (substr($error,length($error)-3,length($error)-1) eq "ppm") {
		$mass_error  = substr($error,0,length($error)-4);
		$type = "ppm";
	} elsif (substr($error,length($error)-2,length($error)-1) eq "Da") {
		$mass_error  = substr($error,0,length($error)-3);
		$type = "Da";
		if ($type eq "ppm") {
			for (my $i=0;$i< @mass_data;$i++) {
				$mass_data[$i][2] = ppm_error_to_mass($mass_data[$i][2]);
			}
		} elsif ($type eq "Da") {
			for (my $i=0;$i< @mass_data;$i++) {
				$mass_data[$i][2] = Da_error_to_mass($mass_data[$i][2]);
			}
		}
	# check if unit of mass error has been given	
	} else {
		print "\n","unit of mass error is not given or not given correctly!","\n\n";
		exit usage();
	}
	sub Da_error_to_mass {
		my ($mass_cal) = @_;
		my ($mass_exact) = $mass_cal + $mass_error;
		return $mass_exact;
	} 
	sub ppm_error_to_mass {
		my ($mass_cal) = @_;
		my ($mass_exact) = (10^6 * $mass_cal) / (10^6 - $mass_error);
		return $mass_exact;
	}
}


###################################################
############# sliding window on bins ##############
###################################################

### calculate m/z values on all data
for (my $i=0;$i< @mass_data;$i++) {
	$mass_data[$i][6] = $mass_data[$i][2]/$mass_data[$i][3];
}
### sort mass data by m/z values
@mass_data = sort {$a->[6] <=> $b->[6]} @mass_data;

### if user doesn't define the mass range --> output all the m/z values
$mass_range_min = $mass_data[0][6];
$mass_range_max = $mass_data[scalar(@mass_data)-1][6];

### report peptides counts in m/z ranges by bins
my @pepcounts_mz; # array for saving results
my $first_half_pep_counts = 0;
my $second_half_pep_counts = 0;
my $bin_counts = 0;
my $min = $mass_range_min - ($bin_size/2);
my $max = $mass_range_min;


for (my $i=1;$i<@mass_data-1;$i++) {
	# see if the bin is in the user-defined range
	if ($max <= $mass_range_max + $bin_size/2) {
		# sum up the peptides counts in the bin
		if ($mass_data[$i][6] >= $min and $mass_data[$i][6] < $max ) {
			$second_half_pep_counts += $mass_data[$i][1];
		} elsif ($mass_data[$i][6] >= $max ) {
			# see if it is the first bin in the loop
			if ($bin_counts == 0) {
				$first_half_pep_counts = $second_half_pep_counts;
				$bin_counts ++;
				$min = $max;
				$max = $min + ($bin_size/2);
				$i--;
			} else {
				$pepcounts_mz[$bin_counts-1][0] = $min;
				$pepcounts_mz[$bin_counts-1][1] = $first_half_pep_counts + $second_half_pep_counts;
				$bin_counts ++;
				$first_half_pep_counts = $second_half_pep_counts;
				$second_half_pep_counts = 0;
				$min = $max;
				$max = $min + ($bin_size/2);				
				$i--;
			}
		}
	}
}

### generate the remained bins in case that the user defined range beyonds the m/z value
while ($max <= $mass_range_max + $bin_size/2) {
	$pepcounts_mz[$bin_counts-1][0] = $min;
	$pepcounts_mz[$bin_counts-1][1] = 0;
	$bin_counts++;
	$min = $max;
	$max = $min + ($bin_size/2);
}


###################################################
###################### output #####################
###################################################

open (OFILE,'>',$filename_output);
print OFILE "m/z values","\t","peptides number","\t","(bin size = ${bin_size})","\n";
	for (my $i=0;$i<@pepcounts_mz;$i++) {
		print OFILE $pepcounts_mz[$i][0],"\t",$pepcounts_mz[$i][1],"\n";
	}
close OFILE;

print 
	"Generate output file successfully!","\n",
	"mass data counts:","\t",scalar(@mass_data),"\n",
	"mass range:","\t",$mass_range_min," - ",$mass_range_max,"\n",
	"bin size:","\t",$bin_size,"\n",
	"mass error:","\t",$error,"\n";



